### ISSUE TITLE
How are values stored in bufferData?

### ISSUE THREAD

**Issue by bmonty** [brenca/sdrjs#1]
My understanding is the rtl-sdr provides I/Q samples.  How are the samples stored in the Buffer created by the sdrjs wrapper?  How can I recover the individual I/Q samples?

**Comment by brenca** [comment]
The `Buffer` that's created contains the data from rtl-sdr without any transformation at all. I've been trying to mirror the (`adsb` sample app)[https://github.com/steve-m/librtlsdr/blob/master/src/rtl_adsb.c], and I've been successful at decoding the data with the I/Q to magnitude function that's in there.
